#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

cp 0/U.orig 0/U
cp 0/p.orig 0/p
runApplication blockMesh
decomposePar
mpirun -np 12 icoFoam -parallel
reconstructPar

// runApplication $application -withFunctionObjects -writePhi -writep
// runApplication postProcess -func streamFunction

#------------------------------------------------------------------------------
